import mongoose from "../../database/mongo";
import Course from "../../models/Course";
import Instructor from "../../models/Instructor";
import User from "../../models/User";

const cursos: any[] = [
  // Carlos Souza
  {
    title: "Node.js para Iniciantes",
    description:
      "Curso introdutório de Node.js para quem está começando no backend.",
    category: null,
    subcategory: "",
    language: "Português",
    price: 120,
    thumbnail: "https://img-cursos.com/nodejs-iniciantes.png",
    level: "beginner",
    certificates: [],
    comments: [],
    instructorId: [],
    playlistId: [],
    ratingAverage: 4.7,
    published: true,
    url: "https://plataforma.com/cursos/nodejs-iniciantes",
    releaseDate: new Date("2025-01-10"),
  },
  {
    title: "JavaScript Moderno e Avançado",
    description:
      "Aprofunde-se em JavaScript moderno, ES6+ e técnicas avançadas.",
    category: null,
    subcategory: "",
    language: "Português",
    price: 150,
    thumbnail: "https://img-cursos.com/js-moderno.png",
    level: "intermediate",
    certificates: [],
    comments: [],
    instructorId: [],
    playlistId: [],
    ratingAverage: 4.8,
    published: true,
    url: "https://plataforma.com/cursos/js-moderno",
    releaseDate: new Date("2025-02-15"),
  },
  {
    title: "Desenvolvimento de APIs RESTful com Express",
    description: "Aprenda a criar APIs RESTful profissionais usando Express.",
    category: null,
    subcategory: "",
    language: "Português",
    price: 200,
    thumbnail: "https://img-cursos.com/apis-express.png",
    level: "intermediate",
    certificates: [],
    comments: [],
    instructorId: [],
    playlistId: [],
    ratingAverage: 4.6,
    published: true,
    url: "https://plataforma.com/cursos/apis-express",
    releaseDate: new Date("2025-03-20"),
  },
  // Juliana Martins
  {
    title: "Fundamentos de Estatística para Iniciantes",
    description: "Estatística básica para quem está começando.",
    category: null,
    subcategory: "",
    language: "Português",
    price: 90,
    thumbnail: "https://img-cursos.com/estatistica-iniciantes.png",
    level: "beginner",
    certificates: [],
    comments: [],
    instructorId: [],
    playlistId: [],
    ratingAverage: 4.5,
    published: true,
    url: "https://plataforma.com/cursos/estatistica-iniciantes",
    releaseDate: new Date("2025-04-10"),
  },
  {
    title: "Matemática Financeira Aplicada",
    description: "Matemática financeira para aplicações práticas.",
    category: null,
    subcategory: "",
    language: "Português",
    price: 110,
    thumbnail: "https://img-cursos.com/matematica-financeira.png",
    level: "intermediate",
    certificates: [],
    comments: [],
    instructorId: [],
    playlistId: [],
    ratingAverage: 4.4,
    published: true,
    url: "https://plataforma.com/cursos/matematica-financeira",
    releaseDate: new Date("2025-05-05"),
  },
  {
    title: "Python Prático para Data Science",
    description: "Python aplicado à ciência de dados.",
    category: null,
    subcategory: "",
    language: "Português",
    price: 180,
    thumbnail: "https://img-cursos.com/python-data-science.png",
    level: "intermediate",
    certificates: [],
    comments: [],
    instructorId: [],
    playlistId: [],
    ratingAverage: 4.9,
    published: true,
    url: "https://plataforma.com/cursos/python-data-science",
    releaseDate: new Date("2025-06-01"),
  },
  // Patrícia Duarte
  {
    title: "Laboratório de Física Experimental",
    description: "Experimentos práticos de física.",
    category: null,
    subcategory: "",
    language: "Português",
    price: 130,
    thumbnail: "https://img-cursos.com/fisica-experimental.png",
    level: "intermediate",
    certificates: [],
    comments: [],
    instructorId: [],
    playlistId: [],
    ratingAverage: 4.3,
    published: true,
    url: "https://plataforma.com/cursos/fisica-experimental",
    releaseDate: new Date("2025-07-10"),
  },
  {
    title: "Cálculo Diferencial e Integral I",
    description: "Primeiro curso de cálculo para universitários.",
    category: null,
    subcategory: "",
    language: "Português",
    price: 140,
    thumbnail: "https://img-cursos.com/calculo-I.png",
    level: "beginner",
    certificates: [],
    comments: [],
    instructorId: [],
    playlistId: [],
    ratingAverage: 4.2,
    published: true,
    url: "https://plataforma.com/cursos/calculo-I",
    releaseDate: new Date("2025-08-01"),
  },
  {
    title: "Mecânica dos Materiais para Engenharia",
    description: "Mecânica aplicada para engenheiros.",
    category: null,
    subcategory: "",
    language: "Português",
    price: 160,
    thumbnail: "https://img-cursos.com/mecanica-materiais.png",
    level: "advanced",
    certificates: [],
    comments: [],
    instructorId: [],
    playlistId: [],
    ratingAverage: 4.1,
    published: true,
    url: "https://plataforma.com/cursos/mecanica-materiais",
    releaseDate: new Date("2025-09-01"),
  },
  // Larissa Ribeiro
  {
    title: "Química Orgânica Estrutural",
    description: "Química orgânica com foco em estrutura molecular.",
    category: null,
    subcategory: "",
    language: "Português",
    price: 170,
    thumbnail: "https://img-cursos.com/quimica-organica.png",
    level: "intermediate",
    certificates: [],
    comments: [],
    instructorId: [],
    playlistId: [],
    ratingAverage: 4.0,
    published: true,
    url: "https://plataforma.com/cursos/quimica-organica",
    releaseDate: new Date("2025-10-01"),
  },
  {
    title: "Biologia Celular e Molecular",
    description: "Estudo das células e moléculas biológicas.",
    category: null,
    subcategory: "",
    language: "Português",
    price: 125,
    thumbnail: "https://img-cursos.com/biologia-celular.png",
    level: "intermediate",
    certificates: [],
    comments: [],
    instructorId: [],
    playlistId: [],
    ratingAverage: 4.5,
    published: true,
    url: "https://plataforma.com/cursos/biologia-celular",
    releaseDate: new Date("2025-11-01"),
  },
  {
    title: "Ecologia Aplicada",
    description: "Ecologia voltada para aplicações práticas.",
    category: null,
    subcategory: "",
    language: "Português",
    price: 135,
    thumbnail: "https://img-cursos.com/ecologia-aplicada.png",
    level: "intermediate",
    certificates: [],
    comments: [],
    instructorId: [],
    playlistId: [],
    ratingAverage: 4.6,
    published: true,
    url: "https://plataforma.com/cursos/ecologia-aplicada",
    releaseDate: new Date("2025-12-01"),
  },
  // Isabela Nunes
  {
    title: "História do Brasil: Da Colônia à República",
    description: "Panorama histórico do Brasil.",
    category: null,
    subcategory: "",
    language: "Português",
    price: 80,
    thumbnail: "https://img-cursos.com/historia-brasil.png",
    level: "beginner",
    certificates: [],
    comments: [],
    instructorId: [],
    playlistId: [],
    ratingAverage: 4.3,
    published: true,
    url: "https://plataforma.com/cursos/historia-brasil",
    releaseDate: new Date("2026-01-01"),
  },
  {
    title: "Sociologia Contemporânea e Problemas Sociais",
    description: "Sociologia aplicada aos problemas atuais.",
    category: null,
    subcategory: "",
    language: "Português",
    price: 95,
    thumbnail: "https://img-cursos.com/sociologia-contemporanea.png",
    level: "intermediate",
    certificates: [],
    comments: [],
    instructorId: [],
    playlistId: [],
    ratingAverage: 4.2,
    published: true,
    url: "https://plataforma.com/cursos/sociologia-contemporanea",
    releaseDate: new Date("2026-02-01"),
  },
  {
    title: "Introdução à Filosofia: Pensamento Ocidental",
    description: "Filosofia ocidental desde a antiguidade.",
    category: null,
    subcategory: "",
    language: "Português",
    price: 105,
    thumbnail: "https://img-cursos.com/filosofia-ocidental.png",
    level: "beginner",
    certificates: [],
    comments: [],
    instructorId: [],
    playlistId: [],
    ratingAverage: 4.4,
    published: true,
    url: "https://plataforma.com/cursos/filosofia-ocidental",
    releaseDate: new Date("2026-03-01"),
  },
];

async function populateCourses() {
  // Remove todos os cursos existentes antes de inserir novos
  await mongoose.connection.dropCollection("courses").catch(() => {});
  await mongoose.connection;
  await Course.insertMany(cursos);
  console.log("\x1b[32m✔ Cursos inseridos com sucesso!\x1b[0m");
  await mongoose.connection.close();
  process.exit();
}

populateCourses();
